/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import curtain from "./curtain.glb";

export default function Curtain({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(curtain);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 6.33]}>
          <mesh
            geometry={nodes.Stage_Curtains_0.geometry}
            material={materials.beams}
            position={[0, -10.21, 0]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/curtain2.glb");
