/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import car1 from "./car1.glb";
export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(car1);
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -0.56, -0.01]} scale={1.13}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
        <mesh
          geometry={nodes.Cube_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Cube_3.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Cube_4.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.Cube_5.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube_6.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Cube_7.geometry}
          material={materials["Material.008"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(car1);
